name: Kernel-Bakery

on:
  watch:
    types: [started]
    
env:
  KERNEL_SOURCE_URL: https://github.com/MiCode/Xiaomi_Kernel_OpenSource/
  KERNEL_SOURCE_BRANCH: dipper-q-oss
  DEFCONFIG_NAME: dipper_user_defconfig
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
         
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install build-essential cpio liblz4-dev zipalign p7zip fakeroot gcc make bc curl git zip
      
       - name: Clone Build ToolChain
         run: |
            git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9.git Toolchain
         
       - name: Clone Kernel Source Code
         run: |
            git clone $KERNEL_SOURCE_URL -b $KERNEL_SOURCE_BRANCH Kernel
       
       - name: Make Kernel
         run: |
            cd Kernel
            export ARCH=arm64
            export SUBARCH=arm64
            export CROSS_COMPILE=aarch64-linux-android-
            export PATH=../Toolchain/bin
            make $DEFCONFIG_NAME
            make
